server:
  port: 80
logging:
  level:
    root: warn
    org.dreamlife.hippocampus.apigateway: info
dubbo:
  application:
    name: apiGateway
  registry:
    address: zookeeper://127.0.0.1:2181
  protocol:
    name: dubbo
    port: 20881
flowlimit:
  rules:
  #regex 匹配url的规则
  - pattern: ".*"
    key: group1
    tps: 200